apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJUM05qYUMweE9tZG9jRjh4T1RKTVZubERWRFUyUTBjME9VNTZNM1UzVTIxMlJEZ3lVbEpDY1dVd1IwczBObkU9In19fQ==
type: kubernetes.io/dockerconfigjson
